export const bookTitles = {
    0: "My Brilliant Friend",
    1: "The Warmth of Other Suns",
    2: "Wolf Hall",
    3: "The Known World",
    4: "The Corrections",
    5: "2666",
    6: "The Underground Railroad",
    7: "Austerlitz",
    8: "Never Let Me Go",
    9: "Gilead",
    10: "The Brief Wondrous Life of Oscar Wao",
    11: "The Year of Magical Thinking",
    12: "The Road",
    13: "Outline",
    14: "Pachinko",
    15: "The Amazing Adventures of Kavalier & Clay",
    16: "The Sellout",
    17: "Lincoln in the Bardo",
    18: "Say Nothing",
    19: "Erasure",
    20: "Evicted",
    21: "Behind the Beautiful Forevers",
    22: "Hateship, Friendship, Courtship, Loveship, Marriage",
    23: "The Overstory",
    24: "Random Family",
    25: "Atonement",
    26: "Americanah",
    27: "Cloud Atlas",
    28: "The Last Samurai",
    29: "Sing, Unburied, Sing",
    30: "White Teeth",
    31: "The Line of Beauty",
    32: "Salvage the Bones",
    33: "Citizen",
    34: "Fun Home",
    35: "Between the World and Me",
    36: "The Years",
    37: "The Savage Detectives",
    38: "A Visit From the Goon Squad",
    39: "H Is for Hawk",
    40: "Small Things Like These",
    41: "A Brief History of Seven Killings",
    42: "Postwar",
    43: "The Fifth Season",
    44: "The Argonauts",
    45: "The Goldfinch",
    46: "A Mercy",
    47: "Persepolis",
    48: "The Vegetarian",
    49: "Trust",
    50: "Life After Life",
    51: "Train Dreams",
    52: "Runaway",
    53: "Tenth of December",
    54: "The Looming Tower",
    55: "The Flamethrowers",
    56: "Nickel and Dimed",
    57: "Stay True",
    58: "Middlesex",
    59: "Heavy",
    60: "Demon Copperhead",
    61: "10:04",
    62: "Veronica",
    63: "The Great Believers",
    64: "The Plot Against America",
    65: "We the Animals",
    66: "Far From the Tree",
    67: "The Friend",
    68: "The New Jim Crow",
    69: "All Aunt Hagar’s Children",
    70: "The Copenhagen Trilogy",
    71: "Secondhand Time",
    72: "The Passage of Power",
    73: "Olive Kitteridge",
    74: "Exit West",
    75: "Tomorrow, and Tomorrow, and Tomorrow",
    76: "An American Marriage",
    77: "Septology",
    78: "A Manual for Cleaning Women",
    79: "The Story of the Lost Child",
    80: "Pulphead",
    81: "Hurricane Season",
    82: "When We Cease to Understand the World",
    83: "The Emperor of All Maladies",
    84: "Pastoralia",
    85: "Frederick Douglass",
    86: "Detransition, Baby",
    87: "The Collected Stories of Lydia Davis",
    88: "The Return",
    89: "The Sympathizer",
    90: "The Human Stain",
    91: "The Days of Abandonment",
    92: "Station Eleven",
    93: "On Beauty",
    94: "Bring Up the Bodies",
    95: "Wayward Lives, Beautiful Experiments",
    96: "Men We Reaped",
    97: "Bel Canto",
    98: "How to Be Both",
    99: "Tree of Smoke",
}